/**
 * Tink Risk & Verification Reports
 *
 * Five read-only report APIs that return pre-generated analysis reports.
 * Reports are immutable once created and are cached for 24 hours.
 *
 * - IncomeCheck          — income stream analysis and PDF export
 * - ExpenseCheck         — categorised expense analysis
 * - RiskInsights         — financial risk scoring
 * - RiskCategorisation   — transaction-level risk categories
 * - BusinessAccountCheck — business account ownership verification
 *
 * https://docs.tink.com/api
 */
import type { HttpClient } from "../utils/http";
import type {
  IncomeCheckReport,
  ExpenseCheckReport,
  RiskInsightsReport,
  RiskCategorisationReport,
  BusinessAccountCheckReport,
} from "../types";

// =============================================================================
// IncomeCheck
// =============================================================================

/**
 * Access income verification reports.
 *
 * Reports are generated by Tink after the user connects their bank account
 * and you request an income check. Once created, reports are immutable.
 *
 * https://docs.tink.com/api#income-check
 */
export class IncomeCheck {
  constructor(private readonly http: HttpClient) {}

  /**
   * Retrieves an income verification report by ID.
   * The report contains income streams, total monthly income, and metadata.
   *
   * @param reportId - Income check report ID
   */
  async getReport(reportId: string): Promise<IncomeCheckReport> {
    return this.http.get<IncomeCheckReport>(`/v2/income-checks/${reportId}`);
  }

  /**
   * Downloads an income check report as a PDF binary.
   * Useful for displaying or archiving the report for compliance purposes.
   *
   * @param reportId - Income check report ID
   * @returns ArrayBuffer containing the PDF bytes
   *
   * @example
   * ```ts
   * const pdfBuffer = await tink.incomeCheck.getReportPdf(reportId);
   * const blob = new Blob([pdfBuffer], { type: "application/pdf" });
   * ```
   */
  async getReportPdf(reportId: string): Promise<ArrayBuffer> {
    return this.http.get<ArrayBuffer>(`/v2/income-checks/${reportId}:generate-pdf`);
  }
}

// =============================================================================
// ExpenseCheck
// =============================================================================

/**
 * Access expense analysis reports.
 *
 * Reports contain categorised expense data generated from the user's
 * transaction history.
 *
 * https://docs.tink.com/api#expense-check
 */
export class ExpenseCheck {
  constructor(private readonly http: HttpClient) {}

  /**
   * Retrieves an expense check report by ID.
   *
   * @param reportId - Expense check report ID
   */
  async getReport(reportId: string): Promise<ExpenseCheckReport> {
    return this.http.get<ExpenseCheckReport>(`/risk/v1/expense-checks/${reportId}`);
  }
}

// =============================================================================
// RiskInsights
// =============================================================================

/**
 * Access financial risk insights reports.
 *
 * Reports contain risk scores, anomaly signals, and financial health indicators
 * based on the user's banking data.
 *
 * https://docs.tink.com/api#risk-insights
 */
export class RiskInsights {
  constructor(private readonly http: HttpClient) {}

  /**
   * Retrieves a risk insights report by ID.
   *
   * @param reportId - Risk insights report ID
   */
  async getReport(reportId: string): Promise<RiskInsightsReport> {
    return this.http.get<RiskInsightsReport>(`/risk/v1/risk-insights/${reportId}`);
  }
}

// =============================================================================
// RiskCategorisation
// =============================================================================

/**
 * Access transaction-level risk categorisation reports.
 *
 * Reports assign risk categories to individual transactions,
 * useful for fraud detection and credit risk assessment.
 *
 * https://docs.tink.com/api#risk-categorisation
 */
export class RiskCategorisation {
  constructor(private readonly http: HttpClient) {}

  /**
   * Retrieves a risk categorisation report by ID.
   *
   * @param reportId - Risk categorisation report ID
   */
  async getReport(reportId: string): Promise<RiskCategorisationReport> {
    return this.http.get<RiskCategorisationReport>(
      `/risk/v2/risk-categorisation/reports/${reportId}`
    );
  }
}

// =============================================================================
// BusinessAccountCheck
// =============================================================================

/**
 * Access business account verification reports.
 *
 * Verifies ownership and details of business bank accounts —
 * similar to Account Check but for corporate/business accounts.
 *
 * https://docs.tink.com/api#business-account-check
 */
export class BusinessAccountCheck {
  constructor(private readonly http: HttpClient) {}

  /**
   * Retrieves a business account verification report by ID.
   *
   * @param reportId - Business account check report ID
   */
  async getReport(reportId: string): Promise<BusinessAccountCheckReport> {
    return this.http.get<BusinessAccountCheckReport>(
      `/data/v1/business-account-verification-reports/${reportId}`
    );
  }
}
